version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: prod.dockerfile
    image: horizon_local_server
    container_name: server
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
    env_file:
      - .envs/local
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local



  client:
    build:
      context: ./client
      dockerfile: prod.dockerfile
    image: horizon_local_client
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
    ports:
      - 80:80


  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/local

volumes:
  postgres_data: { }