version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: prod.dockerfile
    image: horizon_server
    container_name: horizon_server
    depends_on:
      - db
    env_file:
      - .envs/.prod/.django
      - .envs/.prod/.postgres
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local



  client:
    build:
      context: ./client
      dockerfile: prod.dockerfile
    image: horizon_client
    container_name: horizon_client
    depends_on:
      - server
    env_file:
      - .envs/.prod/.vue
    ports:
      - 80:80


  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.prod/.postgres

volumes:
  postgres_data: { }