version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: local.dockerfile
    image: horizon_server
    container_name: horizon_server
    depends_on:
      - db
    volumes:
      - ./server:/app
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local


  client:
    build:
      context: ./client
      dockerfile: local.dockerfile
    image: horizon_client
    container_name: horizon_client
    depends_on:
      - server
    volumes:
      - ./client:/app
    ports:
      - 8080:8080
    command: npm run serve


  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.local/.postgres


volumes:
  postgres_data: { }