version: '3.9'

services:
  server:
    build: ./server
    image: horizon_local_server
    container_name: server
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local


  client:
    build: ./client
    image: horizon_local_client
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
    ports:
      - 8080:8080
    command: npm run serve


  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.local/.postgres

volumes:
  postgres_data: { }