version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: prod.dockerfile
    image: horizon_local_server
    container_name: server
    depends_on:
      - db
    env_file:
      - .envs/.prod/.django
      - .envs/.prod/.postgres
    ports:
      - 8000:8000
    command: gunicorn --bind :8000 --workers 3 --env DJANGO_SETTINGS_MODULE=config.settings.local config.wsgi:application


  client:
    build:
      context: ./client
      dockerfile: prod.dockerfile
    image: horizon_local_client
    depends_on:
      - server
    env_file:
      - .envs/.prod/.vue
    ports:
      - 80:80


  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.prod/.postgres


volumes:
  postgres_data: { }