# Generated by Django 3.1.3 on 2020-12-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcoordinate',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fieldcoordinate',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fieldcoordinate',
            name='x',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='fieldcoordinate',
            name='y',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=25, null=True),
        ),
    ]
