# Generated by Django 3.1.7 on 2021-04-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210405_1358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wellcase',
            unique_together={('name', 'well')},
        ),
    ]
