# Generated by Django 3.1.7 on 2021-04-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210405_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellperforation',
            name='bot_md',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wellperforation',
            name='perforator_type',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='wellperforation',
            name='top_md',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
