# Generated by Django 3.1.3 on 2021-03-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201222_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcoordinate',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldcoordinate',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldcoordinate',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldcoordinate',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inclinometry',
            name='azi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inclinometry',
            name='inc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inclinometry',
            name='md',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mer',
            name='production',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mer',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='dynamic_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='static_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='alt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='bottom',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='pad',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='bot_md',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='bot_tvd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='h',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='top_md',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='top_tvd',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='WellPump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('md', models.FloatField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('diameter', models.FloatField(null=True)),
                ('well', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.well')),
            ],
            options={
                'db_table': 'well_pumps',
            },
        ),
        migrations.CreateModel(
            name='WellPerforation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perforator_type', models.CharField(max_length=70)),
                ('hole_diameter', models.FloatField(null=True)),
                ('holes_per_meter', models.FloatField(null=True)),
                ('top_md', models.FloatField(null=True)),
                ('bot_md', models.FloatField(null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_perforations', to='api.well')),
            ],
            options={
                'db_table': 'well_perforations',
            },
        ),
        migrations.CreateModel(
            name='WellCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('diameter', models.FloatField()),
                ('length', models.FloatField(null=True)),
                ('top_md', models.FloatField(null=True)),
                ('bot_md', models.FloatField(null=True)),
                ('cemented', models.BooleanField(null=True)),
                ('cement_top', models.FloatField(null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_cases', to='api.well')),
            ],
            options={
                'db_table': 'well_cases',
            },
        ),
    ]
