# Generated by Django 3.1.7 on 2021-04-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210405_1422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='well',
            unique_together=set(),
        ),
    ]
