# Generated by Django 3.1.7 on 2021-04-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210407_0936'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='well',
            unique_together={('name', 'field')},
        ),
    ]
