# Generated by Django 3.1.3 on 2021-03-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
