# Generated by Django 3.1.3 on 2020-11-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclinometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('inc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('azi', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='api.well')),
            ],
            options={
                'db_table': 'inclinometry',
            },
        ),
    ]
