# Generated by Django 3.1.3 on 2020-11-27 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inclinometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclinometry',
            name='azi',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inclinometry',
            name='inc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inclinometry',
            name='md',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dynamic_level', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('static_level', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('work_days', models.IntegerField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.well')),
            ],
            options={
                'db_table': 'rates',
            },
        ),
        migrations.CreateModel(
            name='Mer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('production', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('work_days', models.IntegerField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.well')),
            ],
            options={
                'db_table': 'mer',
                'unique_together': {('well', 'date')},
            },
        ),
    ]
