# Generated by Django 3.1.3 on 2020-11-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201127_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='work_days',
        ),
        migrations.AlterField(
            model_name='inclinometry',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inc', to='api.well'),
        ),
        migrations.AlterField(
            model_name='mer',
            name='work_days',
            field=models.IntegerField(null=True),
        ),
    ]
