# Generated by Django 3.1.3 on 2020-12-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201130_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='api.field')),
            ],
            options={
                'db_table': 'field_coordinates',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('top_md', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bot_md', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('top_tvd', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bot_tvd', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('h', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.well')),
            ],
            options={
                'db_table': 'zones',
                'unique_together': {('name', 'well')},
            },
        ),
    ]
