# Generated by Django 3.1.3 on 2020-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fieldcoordinate_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='pad',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
